# Ação de Revisão de Dependências
#
# Esta ação irá escanear arquivos de manifesto de dependências que mudam como parte de um Pull Request,
# mostrando versões conhecidas como vulneráveis dos pacotes declarados ou atualizados no PR.
# Uma vez instalada, se a execução do workflow for marcada como obrigatória, PRs que introduzem pacotes vulneráveis
# conhecidos serão bloqueados de serem mesclados.
#
# Repositório fonte: https://github.com/actions/dependency-review-action
# Documentação pública: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Revisão de dependências'
on:
  pull_request:
    branches: [ "main", "desenvolvimento", "testes" ]

# Se estiver usando uma ação de submissão de dependências neste workflow, esta permissão precisará ser definida como:
#
# permissions:
#   contents: write
#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api
permissions:
  contents: read
  # Permissões de escrita para pull-requests são necessárias para usar a opção `comment-summary-in-pr`, comente se não estiver usando esta opção
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Fazer checkout do repositório'
        uses: actions/checkout@v4
      - name: 'Revisão de dependências'
        uses: actions/dependency-review-action@v4
        # Opções comumente habilitadas, veja https://github.com/actions/dependency-review-action#configuration-options para todas as opções disponíveis.
        with:
          comment-summary-in-pr: always
        #   fail-on-severity: moderate
        #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
        #   retry-on-snapshot-warnings: true
